// <auto-generated>
// 由 klink bot/tools/gen-gameplay-tags.py 从 ref/kards-sim/cards.json 生成。
// 不要手改；要改就改脚本再跑（见脚本头部注释：客户端的 pak 里没有这张表）。
// </auto-generated>
#nullable enable

namespace KLink.Bot.Effects;

/// <summary>
/// 卡名 → gameplay tag（170 张卡 / 18 个 tag）。
///
/// 用途：实现 <c>getHasGameplayTag</c>。卡牌蓝图用它判子类型，例如
/// <c>card_unit_214th_amur</c> 判 <c>subtype.t34</c>、
/// <c>card_event_committed_crew</c> 判 <c>subtype.spitfire</c>。
///
/// ⚠️ 变体卡（<c>xxx_bal</c> / <c>xxx_vet</c>）在这里**没有条目** ——
/// 查表前必须先用 <c>CardDatabase.ResolveBaseName</c> 剥后缀，
/// 这和 <c>KismetLibrary</c> 找蓝图用的是同一套回退规则。
/// </summary>
internal static class GameplayTagTable
{
    private static readonly Dictionary<string, string[]> TagsByCard = new(StringComparer.Ordinal)
    {
        ["card_event_admiral_hipper"] = ["subtype.navy"],
        ["card_event_air_land_sea"] = ["ability.develop"],
        ["card_event_baker_street_irregulars"] = ["ability.develop"],
        ["card_event_betasom"] = ["ability.develop"],
        ["card_event_bismarck"] = ["subtype.navy"],
        ["card_event_blitz_doctrine"] = ["ability.develop"],
        ["card_event_bomber_mafia"] = ["ability.develop"],
        ["card_event_bpf"] = ["ability.develop"],
        ["card_event_contest_doctrine"] = ["ability.develop"],
        ["card_event_cruiser_scouts"] = ["ability.forecast"],
        ["card_event_drive_into_the_sea"] = ["ability.bond"],
        ["card_event_hmas_warramunga"] = ["subtype.navy"],
        ["card_event_hms_belfast"] = ["subtype.navy"],
        ["card_event_hms_formidable"] = ["subtype.navy"],
        ["card_event_hms_hermes"] = ["subtype.navy"],
        ["card_event_hms_illustrious"] = ["subtype.navy"],
        ["card_event_hms_spectre"] = ["subtype.navy"],
        ["card_event_home_guard"] = ["ability.bond"],
        ["card_event_ijn_akagi"] = ["subtype.navy"],
        ["card_event_ijn_shirakumo"] = ["subtype.navy"],
        ["card_event_imperial_research"] = ["subtype.research"],
        ["card_event_ingenuity"] = ["ability.develop"],
        ["card_event_mikura"] = ["subtype.navy"],
        ["card_event_orp_blyskawica"] = ["subtype.navy"],
        ["card_event_orp_general_haller"] = ["subtype.navy"],
        ["card_event_orp_orzel"] = ["subtype.navy"],
        ["card_event_overcast"] = ["ability.forecast"],
        ["card_event_pams"] = ["ability.develop"],
        ["card_event_pilot_escape"] = ["ability.develop"],
        ["card_event_prinz_eugen"] = ["subtype.navy"],
        ["card_event_rain1_mist"] = ["autoplay"],
        ["card_event_rain2_deluge"] = ["subtype.lightWeather", "subtype.rain"],
        ["card_event_rain2_deluge2"] = ["subtype.lightWeather", "subtype.rain"],
        ["card_event_rain2_deluge3"] = ["subtype.lightWeather", "subtype.rain"],
        ["card_event_rain3_torrential_rain"] = ["subtype.mediumWeather", "subtype.rain"],
        ["card_event_rain3_torrential_rain2"] = ["subtype.mediumWeather", "subtype.rain"],
        ["card_event_rain3_torrential_rain3"] = ["subtype.mediumWeather", "subtype.rain"],
        ["card_event_rain4_monsoon_rain"] = ["subtype.heavyWeather", "subtype.rain"],
        ["card_event_rain4_monsoon_rain2"] = ["subtype.heavyWeather", "subtype.rain"],
        ["card_event_rain4_monsoon_rain3"] = ["subtype.heavyWeather", "subtype.rain"],
        ["card_event_reich_research"] = ["subtype.research"],
        ["card_event_resistance_new"] = ["autoplay"],
        ["card_event_retribution"] = ["ability.develop"],
        ["card_event_retribution1"] = ["subtype.retribution"],
        ["card_event_retribution10"] = ["subtype.retribution"],
        ["card_event_retribution12"] = ["subtype.retribution"],
        ["card_event_retribution13"] = ["subtype.retribution"],
        ["card_event_retribution2"] = ["subtype.retribution"],
        ["card_event_retribution3"] = ["subtype.retribution"],
        ["card_event_retribution4"] = ["ability.develop", "subtype.retribution"],
        ["card_event_retribution5"] = ["subtype.retribution"],
        ["card_event_retribution6"] = ["subtype.retribution"],
        ["card_event_retribution7"] = ["subtype.retribution"],
        ["card_event_retribution8"] = ["subtype.retribution"],
        ["card_event_retribution9"] = ["subtype.retribution"],
        ["card_event_rm_bersaglieri"] = ["subtype.navy"],
        ["card_event_rm_roma"] = ["subtype.navy"],
        ["card_event_royal_research"] = ["subtype.research"],
        ["card_event_sea_embargo"] = ["ability.develop"],
        ["card_event_shinano"] = ["subtype.navy"],
        ["card_event_soviet_military_research"] = ["subtype.research"],
        ["card_event_storm1_gale"] = ["autoplay"],
        ["card_event_storm2_thunderstorm"] = ["subtype.lightWeather", "subtype.storm"],
        ["card_event_storm2_thunderstorm2"] = ["subtype.lightWeather", "subtype.storm"],
        ["card_event_storm2_thunderstorm3"] = ["subtype.lightWeather", "subtype.storm"],
        ["card_event_storm3_tropical_storm"] = ["subtype.mediumWeather", "subtype.storm"],
        ["card_event_storm3_tropical_storm2"] = ["subtype.mediumWeather", "subtype.storm"],
        ["card_event_storm3_tropical_storm3"] = ["subtype.mediumWeather", "subtype.storm"],
        ["card_event_storm4_cyclone"] = ["subtype.heavyWeather", "subtype.storm"],
        ["card_event_storm4_cyclone2"] = ["subtype.heavyWeather", "subtype.storm"],
        ["card_event_storm4_cyclone3"] = ["subtype.heavyWeather", "subtype.storm"],
        ["card_event_strike_group"] = ["ability.showwhendrawn"],
        ["card_event_sunny1_blue_sky"] = ["autoplay"],
        ["card_event_sunny2_heatwave"] = ["subtype.lightWeather", "subtype.sunny"],
        ["card_event_sunny2_heatwave2"] = ["subtype.lightWeather", "subtype.sunny"],
        ["card_event_sunny2_heatwave3"] = ["subtype.lightWeather", "subtype.sunny"],
        ["card_event_sunny3_jungle_fever"] = ["subtype.mediumWeather", "subtype.sunny"],
        ["card_event_sunny3_jungle_fever2"] = ["subtype.mediumWeather", "subtype.sunny"],
        ["card_event_sunny3_jungle_fever3"] = ["subtype.mediumWeather", "subtype.sunny"],
        ["card_event_sunny4_scorching_sun"] = ["subtype.heavyWeather", "subtype.sunny"],
        ["card_event_sunny4_scorching_sun2"] = ["subtype.heavyWeather", "subtype.sunny"],
        ["card_event_sunny4_scorching_sun3"] = ["subtype.heavyWeather", "subtype.sunny"],
        ["card_event_task_force_44"] = ["ability.forecast"],
        ["card_event_the_land_girls"] = ["ability.bond"],
        ["card_event_the_rock_of_gibraltar"] = ["ability.develop"],
        ["card_event_tirpitz"] = ["subtype.navy"],
        ["card_event_u_16"] = ["subtype.navy"],
        ["card_event_u_375"] = ["subtype.navy"],
        ["card_event_u_99"] = ["subtype.navy"],
        ["card_event_us_military_research"] = ["subtype.research"],
        ["card_event_us_weather_bureau"] = ["ability.forecast"],
        ["card_event_uss_arcfish"] = ["subtype.navy"],
        ["card_event_uss_fitch"] = ["subtype.navy"],
        ["card_event_uss_missouri"] = ["subtype.navy"],
        ["card_event_uss_sullivans"] = ["subtype.navy"],
        ["card_event_uss_yorktown"] = ["subtype.navy"],
        ["card_event_volunteer_corps_home"] = ["ability.bond"],
        ["card_event_yamato"] = ["subtype.navy"],
        ["card_unit_151st_infantry_regiment"] = ["ability.develop"],
        ["card_unit_15_aufklarungs"] = ["ability.develop"],
        ["card_unit_18_infantry_regiment"] = ["ability.bond"],
        ["card_unit_18th_bersaglieri"] = ["ability.bond"],
        ["card_unit_199th_rifle_regiment"] = ["ability.bond"],
        ["card_unit_1er_marins_commandos"] = ["subtype.commando"],
        ["card_unit_1st_defense_battalion"] = ["ability.bond"],
        ["card_unit_211th_tokyo"] = ["ability.bond"],
        ["card_unit_27_fusiliers"] = ["ability.bond"],
        ["card_unit_289th_gatchina"] = ["ability.bond"],
        ["card_unit_40_panzergrenadier"] = ["ability.bond"],
        ["card_unit_40_royal_marine"] = ["subtype.commando"],
        ["card_unit_41st_infantry_regiment"] = ["ability.develop"],
        ["card_unit_43_infantry_regiment"] = ["ability.bond"],
        ["card_unit_4th_alabama"] = ["ability.showwhendrawn"],
        ["card_unit_573rd_rifles"] = ["ability.bond"],
        ["card_unit_5th_bersaglieri"] = ["ability.bond"],
        ["card_unit_740th_rifle_regiment"] = ["ability.develop"],
        ["card_unit_74_panzergrenadier"] = ["ability.bond"],
        ["card_unit_92_infantry_regiment"] = ["ability.develop"],
        ["card_unit_9th_bersaglieri"] = ["ability.bond"],
        ["card_unit_9th_guards_regiment"] = ["ability.bond"],
        ["card_unit_british_sherman_firefly"] = ["subtype.sherman"],
        ["card_unit_calliope"] = ["subtype.sherman"],
        ["card_unit_coastwatchers"] = ["ability.forecast"],
        ["card_unit_commandos"] = ["subtype.commando"],
        ["card_unit_commandos_cam1"] = ["subtype.commando"],
        ["card_unit_defiant_mk_i"] = ["ability.bond"],
        ["card_unit_devils_brigade"] = ["subtype.commando"],
        ["card_unit_duck_us"] = ["ability.forecast"],
        ["card_unit_f6f_hellcat_home"] = ["ability.bond"],
        ["card_unit_hampshire_regiment"] = ["ability.develop"],
        ["card_unit_iosef_stalin_ii_1944"] = ["ability.bond"],
        ["card_unit_kawanishi_h8k"] = ["ability.forecast"],
        ["card_unit_ki_61_i_tei"] = ["ability.bond"],
        ["card_unit_kingfisher_us"] = ["ability.forecast"],
        ["card_unit_kofu_regiment"] = ["ability.bond"],
        ["card_unit_layforce"] = ["ability.bond", "subtype.commando"],
        ["card_unit_m3_lee_home"] = ["ability.bond"],
        ["card_unit_m4_sherman"] = ["subtype.sherman"],
        ["card_unit_m4_sherman_flam"] = ["subtype.sherman"],
        ["card_unit_m4a1"] = ["subtype.sherman"],
        ["card_unit_m4a2"] = ["subtype.sherman"],
        ["card_unit_magnificent_seven"] = ["ability.bond"],
        ["card_unit_no1_commando"] = ["subtype.commando"],
        ["card_unit_no43_commando"] = ["subtype.commando"],
        ["card_unit_no_3_commando"] = ["subtype.commando"],
        ["card_unit_no_46_commando"] = ["subtype.commando"],
        ["card_unit_no_9_commando"] = ["subtype.commando"],
        ["card_unit_pb2y_coronado"] = ["ability.showwhendrawn"],
        ["card_unit_polish_sherman"] = ["subtype.sherman"],
        ["card_unit_raaf_walrus"] = ["ability.forecast"],
        ["card_unit_raf_mustang"] = ["ability.bond"],
        ["card_unit_sherman_firefly_pl"] = ["subtype.sherman"],
        ["card_unit_spitfire"] = ["subtype.spitfire"],
        ["card_unit_spitfire_mk_ii"] = ["subtype.spitfire"],
        ["card_unit_spitfire_mk_iia"] = ["subtype.spitfire"],
        ["card_unit_spitfire_mk_v_pol"] = ["subtype.spitfire"],
        ["card_unit_spitfire_v"] = ["subtype.spitfire"],
        ["card_unit_t_34"] = ["subtype.t34"],
        ["card_unit_t_34_76d"] = ["subtype.t34"],
        ["card_unit_t_34_85"] = ["subtype.t34"],
        ["card_unit_t_34_85_1944"] = ["subtype.t34"],
        ["card_unit_t_34_85_1945"] = ["subtype.t34"],
        ["card_unit_t_34_flame"] = ["subtype.t34"],
        ["card_unit_t_34_pol"] = ["subtype.t34"],
        ["card_unit_t_34eot"] = ["subtype.t34"],
        ["card_unit_the_polar_bears"] = ["ability.bond"],
        ["card_unit_the_professionals"] = ["ability.bond"],
        ["card_unit_usaaf_spitfire_ix"] = ["subtype.spitfire"],
        ["card_unit_valentine_mk_ii"] = ["ability.bond"],
        ["card_unit_yokosuka_e14y"] = ["ability.forecast"],
    };

    /// <summary>这张卡有没有这个 tag（tag 名形如 <c>subtype.t34</c>）。</summary>
    public static bool Has(string cardName, string tag)
    {
        if (cardName.Length == 0 || tag.Length == 0)
        {
            return false;
        }

        foreach (string candidate in Candidates(cardName))
        {
            if (TagsByCard.TryGetValue(candidate, out string[]? tags)
                && Array.IndexOf(tags, tag) >= 0)
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// 这张卡带不带**任意** tag。
    ///
    /// 用途：`getHasGameplayTag` 的 tag 实参在 IR 里可能被丢掉
    /// （`StructConst /Script/GameplayTags.GameplayTag` 被生成器压成了 `{struct:null}`），
    /// 那时只能退一步问「它是不是某种子类型」。**这不是通用正确解**，
    /// 调用点同时会把 `getHasGameplayTag<ir-tag-lost>` 记进未实现统计。
    /// </summary>
    public static bool Any(string cardName)
    {
        foreach (string candidate in Candidates(cardName))
        {
            if (TagsByCard.ContainsKey(candidate))
            {
                return true;
            }
        }

        return false;
    }

    private static IEnumerable<string> Candidates(string cardName)
    {
        yield return cardName;

        string baseName = Cards.CardDatabase.ResolveBaseName(cardName);
        if (!string.Equals(baseName, cardName, StringComparison.Ordinal))
        {
            yield return baseName;
        }
    }
}
