"""从卡牌 CDO 抽出**卡面自带的关键字与重甲**，生成内核用的查表文件。

为什么需要这一步
----------------
`cards.live.json`（`tools/gen-card-db.py` 的产物）里**只有 `hasGuard` 一个布尔字段**，
其余 `hasBlitz` / `hasAmbush` / `hasFury` / `hasSmokescreen` / `hasAlpine` /
`hasMobilize` / `hasSalvage` / `hasShock`、以及 `heavyArmor` **一个都没抽**。
后果（实测，`tools/AuraDiag` 的「卡面关键字诊断」）：
**任何一张卡的 `CardInstance.Keywords` 建出来都是空的**，包括 205 张天生 Blitz 的卡。

这直接卡住两条规则：
1. **召唤失调**（`cardsCheckFunctions::CanAttack` i=2087 / `BP_Logic::CanCardDoAnything`
   i=1445）：判据是 `enterPlayOnTurn == currentTurn && !getHasBlitz()` ——
   `getHasBlitz()` 读不到，所有 Blitz 单位都会被误判成"刚部署、不能打"。
2. **Guard 的嘲讽**（`MatchEngine.LegalTargets` 用 `Keyword.Guard`）——
   128 张带 Guard 的卡全都不生效。

`ref/kards-sim/cards.json` 的 `flags` 里也有这些，但那是别人的产物；
这里直接从**我们自己的** `decompiled/cards.all.json`（pak CDO）抽，可复现。

用法（在仓库根目录）：
    python "klink bot/tools/gen-card-keywords.py"
输出：
    src/KLink.Bot/Cards/CardInnateTable.cs
"""

import json
import io
import sys
from pathlib import Path

SRC = Path("klink bot/decompiled/cards.all.json")
DST = Path("src/KLink.Bot/Cards/CardInnateTable.cs")

# CDO 字段 → 内核 `Keyword.*` 常量名。
# ⚠️ 只映射**内核已经有关键字常量**的那些。
# 2026-09-30（P1）：`Keyword` 补了 Deployment / Destruction / Covert / Pincer / Scrying
# 五个常量，这里同步收录 —— 否则 `hasDeployment` 这类成员读在内核里恒假
# （审计 §4.1 第 1 条：IR 里的成员读 hasCovert(10)/hasDestruction(4)/hasAlpine(2)/
#  hasMobilize(2)/hasDeployment(1) 全部读成 null → 判假）。
BOOL_FLAGS = {
    "hasBlitz": "Blitz",
    "hasGuard": "Guard",
    "hasAmbush": "Ambush",
    "hasFury": "Fury",
    "hasSmokescreen": "Smokescreen",
    "hasAlpine": "Alpine",
    "hasMobilize": "Mobilize",
    "hasSalvage": "Salvage",
    "hasShock": "Shock",
    "hasDeployment": "Deployment",
    "hasDestruction": "Destruction",
    "hasCovert": "Covert",
    "hasPincer": "Pincer",
    "hasScrying": "Scrying",
}


def main():
    if not SRC.exists():
        print(f"找不到 {SRC}（在仓库根目录跑）")
        return 2

    batch = json.loads(SRC.read_text(encoding="utf-8-sig"))
    assets = batch.get("assets", {})

    rows = []
    for path, info in sorted(assets.items()):
        cdo = info.get("cdo") or {}
        name = Path(path).stem
        kws = [kw for flag, kw in BOOL_FLAGS.items()
               if str(cdo.get(flag, "")).strip().lower() in ("true", "1")]
        armor = cdo.get("heavyArmor")
        try:
            armor = int(armor) if armor is not None else 0
        except (TypeError, ValueError):
            armor = 0

        if not kws and armor <= 0:
            continue

        rows.append((name, sorted(kws), armor))

    lines = []
    lines.append("// <auto-generated>")
    lines.append("// 由 klink bot/tools/gen-card-keywords.py 从 decompiled/cards.all.json 生成。")
    lines.append("// 不要手改；要改就改脚本再跑。")
    lines.append("// </auto-generated>")
    lines.append("#nullable enable")
    lines.append("")
    lines.append("namespace KLink.Bot.Cards;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append(f"/// 卡名 → 卡面自带的**关键字**与**重甲点数**（{len(rows)} 张）。")
    lines.append("///")
    lines.append("/// 来源是 pak 里卡牌 CDO 的 <c>has*</c> 布尔字段与 <c>heavyArmor</c> ——")
    lines.append("/// `src/KLink.Bot/Cards/CardDatabase.cs` 用的 `cards.live.json` **只有 `hasGuard`**，")
    lines.append("/// 其余全缺，于是所有卡的 `CardInstance.Keywords` 建出来都是空的（含 205 张天生 Blitz）。")
    lines.append("///")
    lines.append("/// ⚠️ 变体卡（<c>xxx_bal</c> / <c>xxx_vet</c>）在这里没有条目 ——")
    lines.append("/// 查表前先用 <see cref=\"CardDatabase.ResolveBaseName\"/> 剥后缀，")
    lines.append("/// 与 <c>KismetLibrary</c> / <c>GameplayTagTable</c> 用的是同一套回退规则。")
    lines.append("/// </summary>")
    lines.append("internal static class CardInnateTable")
    lines.append("{")
    lines.append("    private static readonly Dictionary<string, (string[] Keywords, int HeavyArmor)> ByCard =")
    lines.append("        new(StringComparer.Ordinal)")
    lines.append("    {")
    for name, kws, armor in rows:
        kw = ", ".join(f'"{k}"' for k in kws)
        lines.append(f'        ["{name}"] = ([{kw}], {armor}),')
    lines.append("    };")
    lines.append("")
    lines.append("    /// <summary>查这张卡自带的关键字与重甲；查不到返回空 / 0。</summary>")
    lines.append("    public static (string[] Keywords, int HeavyArmor) Get(string cardName)")
    lines.append("    {")
    lines.append("        if (cardName.Length > 0 && ByCard.TryGetValue(cardName, out var hit))")
    lines.append("        {")
    lines.append("            return hit;")
    lines.append("        }")
    lines.append("")
    lines.append("        string baseName = CardDatabase.ResolveBaseName(cardName);")
    lines.append("        if (!string.Equals(baseName, cardName, StringComparison.Ordinal)")
    lines.append("            && ByCard.TryGetValue(baseName, out var fallback))")
    lines.append("        {")
    lines.append("            return fallback;")
    lines.append("        }")
    lines.append("")
    lines.append("        return (Array.Empty<string>(), 0);")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")

    import collections
    kc = collections.Counter(k for _, kws, _ in rows for k in kws)
    armor_n = sum(1 for _, _, a in rows if a > 0)
    print(f"写出 {len(rows)} 张卡的先天属性 → {DST}")
    print(f"  带重甲的: {armor_n} 张")
    for k, v in sorted(kc.items()):
        print(f"  {k:<14} {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
