"""生成 `src/KLink.Bot/Cards/CardPoolTable.cs` —— 候选池口径的**数据表**。

为什么要这张表：`BP_CardFunctions::GetAllActiveStaticCards` 的候选池不是"整个卡库"，
它按 ① 卡集（`ECardSetEnum`）② `NotifyCheckCardReserved` ③ `NotifyCheckCardBlacklisted`
三层过滤。前两层要的两份数据在卡库里都没有：

* `ECardSetEnum` 的**数值**：CDO 里只存枚举**名**（`ECardSetEnum::OceaniaStorm`），
  数值只能从蓝图代码里反推（见下面 CARD_SET 的注释）。
* `isReserved`：CDO 的布尔字段（563 张），`cards.json` 没导出。

数据源：`klink bot/decompiled/cards.all.json`（pak CDO 全量 dump）。

用法：
    python gen-card-pool-table.py            # 从仓库根目录跑
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "klink bot" / "decompiled" / "cards.all.json"
DST = ROOT / "src" / "KLink.Bot" / "Cards" / "CardPoolTable.cs"

# `ECardSetEnum` 数值 → CDO 里的枚举名。
#
# 出处（两条互相独立的证据，交叉验证）：
#
# 1. `UIUtilityFunctions.GetCardsetNameByEnum`
#    （`ref/kards-sim/KardsSim/Generated/_deps/UIUtilityFunctions.g.cs:1010`）
#    是一个 23 路的 Select 节点，把 `cardSet` 的**字节值**映射到显示名：
#       0=ALL SETS 1=Base 2=Special 3=OnlySpawnable 4=Candidate 5=Placeholder
#       6=Expansion1 7=Expansion2 8=Allegiance 9=Theaters of War 10=Breakthrough
#       11=Wildcard 12=Legions 13=World at War 14=Core 15=Brothers in Arms
#       16=Winter War 17=Covert Ops 18=Blood & Iron 19=Naval Warfare
#       20=Homefront 21=Oceania Storm
#
# 2. `BP_Logic.LoadAllStaticCards`
#    （`out/bp-logic.json` 的 `LoadAllStaticCards` 字节码 `[120]`..`[174]`，
#     反编译体见 `ref/kards-sim/KardsSim/Generated/_deps/BP_Logic.g.cs:13040+`）
#    在同一段 SwitchEnum 链上给每个数值累加一个 `totalStaticCards.StatCards*`
#    计数器 —— 计数器**名字**直接把数值钉到卡集名上：
#       1→StatCardsBasic 8→StatCardsAllegiance 10→StatCardsBreakthrough
#       12→StatCardsLegions 15→StatCardsBrothersInArms 16→StatCardsWinterWar
#       17→StatCardsCovertOps 18→StatCardsBloodAndIron 19→StatCardsNavalWarfare
#       20→StatCardsHomefront 21→StatCardsOceaniaStorm
#
# 显示名与 CDO 枚举名对不上的那三个，用**目录交叉表**钉死
# （`Cards/<国家>/<目录>/` 与 `cardSet` 枚举名的一致性）：
#       8  Allegiance      ← CDO 名 `Expansion2019`（Britain/Allegiance 下 22 张全是它）
#       9  Theaters of War ← CDO 名 `Campaign2020`（Britain/ToW 下 7 张全是它）
#       13 World at War    ← CDO 名 `WorldAtWar`
#       17 Covert Ops      ← CDO 名 `CurrentExpansion`（Britain/CovertOp 下 15 张全是它）
CARD_SET = {
    "Basic": 1,
    "Special": 2,
    "OnlySpawnable": 3,
    "Candidate": 4,
    "Placeholder": 5,
    "Expansion1": 6,
    "Expansion2": 7,
    "Expansion2019": 8,
    "Campaign2020": 9,
    "Breakthrough": 10,
    "Wildcards": 11,
    "Legions": 12,
    "WorldAtWar": 13,
    "Core": 14,
    "BrothersInArms": 15,
    "WinterWar": 16,
    "CurrentExpansion": 17,
    "BloodAndIron": 18,
    "NavalWarfare": 19,
    "Homefront": 20,
    "OceaniaStorm": 21,
}


def main():
    data = json.loads(SRC.read_text(encoding="utf-8-sig"))
    assets = data["assets"]

    reserved = []
    seen_set = set()
    for info in assets.values():
        cdo = info.get("cdo") or {}
        name = cdo.get("Name")
        if not name:
            continue
        cs = cdo.get("cardSet")
        if cs:
            seen_set.add(cs.split("::")[-1])
        if str(cdo.get("isReserved")).strip().lower() == "true":
            reserved.append(name)

    unknown = sorted(seen_set - set(CARD_SET))
    if unknown:
        print(f"[!] CDO 里出现了映射表里没有的 cardSet: {unknown}", file=sys.stderr)
        return 1

    reserved.sort()

    lines = []
    lines.append("// <auto-generated>")
    lines.append("// 由 klink bot/tools/gen-card-pool-table.py 从 decompiled/cards.all.json 生成。")
    lines.append("// 不要手改；要改就改脚本再跑。")
    lines.append("// </auto-generated>")
    lines.append("#nullable enable")
    lines.append("")
    lines.append("namespace KLink.Bot.Cards;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append("/// **候选池口径**的数据表 —— `BP_CardFunctions.GetAllActiveStaticCards` 的判据来源。")
    lines.append("///")
    lines.append("/// 蓝图原文（`ref/kards-sim/KardsSim/Generated/BP_CardFunctions.g.cs:19104-19338`）：")
    lines.append("/// 遍历 `GameStateRef.GetAllStaticCardsSortedByName()`，按")
    lines.append("/// ① `cardSet`（见 <see cref=\"IsSetInPool\"/>）")
    lines.append("/// ② `NotifyCheckCardReserved`（= `IsCardReserved`，见 <see cref=\"IsReserved\"/>）")
    lines.append("/// ③ `NotifyCheckCardBlacklisted`（服务端 `DSession.cards_blacklist`，离线不可得）")
    lines.append("/// 三层过滤。")
    lines.append("/// </summary>")
    lines.append("internal static class CardPoolTable")
    lines.append("{")
    lines.append("    /// <summary>")
    lines.append("    /// `cardSet` 字符串 → `/Script/KardsCore.ECardSetEnum` 的**数值**。")
    lines.append("    ///")
    lines.append("    /// 数值映射的出处见 `klink bot/tools/gen-card-pool-table.py` 顶部的注释：")
    lines.append("    /// `UIUtilityFunctions.GetCardsetNameByEnum`（字节值→显示名）与")
    lines.append("    /// `BP_Logic.LoadAllStaticCards` 的 `StatCards*` 计数器（字节值→卡集名）两条独立证据。")
    lines.append("    /// 认不出来一律 0（`NotAvailable`）—— 宁可把卡滤掉，也不要猜一个卡集出来。")
    lines.append("    /// </summary>")
    lines.append("    public static int CardSetIdOf(string? cardSet) => cardSet switch")
    lines.append("    {")
    for name in sorted(CARD_SET, key=lambda k: CARD_SET[k]):
        lines.append(f'        "{name}" => {CARD_SET[name]},')
    lines.append("        _ => 0,")
    lines.append("    };")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// `ECardSetEnum::OceaniaStorm`（= 21）现在生效吗 ——")
    lines.append("    /// 蓝图里走的是 `DeckAndCollectionUtilityFunctions.isCardSetConfigActive(21)`：")
    lines.append("    /// 读 `ConfigSubsystem` 的字符串 `oceania_storm_date`，`now > 那个日期` 才算生效")
    lines.append("    /// （`_deps/DeckAndCollectionUtilityFunctions.g.cs:756-803`）。")
    lines.append("    ///")
    lines.append("    /// 本内核没有 `ConfigSubsystem`，所以取**观测证据**代替：")
    lines.append("    /// `out/_server-replays/replay-508065` 里客户端从 `card_event_atlantic_convoy`")
    lines.append("    /// 的候选池（= `GetAllActiveStaticCards` 的子集）抽到了 `card_unit_fifth_ohio`，")
    lines.append("    /// 而那张卡的 `cardSet` 正是 `OceaniaStorm` ⇒ 那一局该卡集**是生效的**。")
    lines.append("    /// </summary>")
    lines.append("    public const bool OceaniaStormActive = true;")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// `GetAllActiveStaticCards` 的第一层判据（`cardSet`）。")
    lines.append("    ///")
    lines.append("    /// ⚠️ 常见误读：数值 15..20 **不是** `includeNotAttainable` 门控的。")
    lines.append("    /// 反编译里只有 2..7 走 `L_08CC`（那个 `if (!includeNotAttainable) 跳过` 的分支），")
    lines.append("    /// 1 / 8 / 9 / 10 / 12 / 13 / 15 / 16 / 17 / 18 / 19 / 20 全部直接落到 `L_01F0`（保留）。")
    lines.append("    /// 不在 SwitchEnum 链上的数值（0 / 11 / 14 / 22+）落到 `L_088C`，**无条件跳过**。")
    lines.append("    /// </summary>")
    lines.append("    public static bool IsSetInPool(string? cardSet, bool includeNotAttainable) =>")
    lines.append("        CardSetIdOf(cardSet) switch")
    lines.append("        {")
    lines.append("            1 or 8 or 9 or 10 or 12 or 13")
    lines.append("                or 15 or 16 or 17 or 18 or 19 or 20 => true,")
    lines.append("            21 => OceaniaStormActive,")
    lines.append("            2 or 3 or 4 or 5 or 6 or 7 => includeNotAttainable,")
    lines.append("            _ => false,")
    lines.append("        };")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// CDO 里 `isReserved = true` 的 563 张卡。")
    lines.append("    ///")
    lines.append("    /// 语义链：`GetAllActiveStaticCards` 的第二层判据调")
    lines.append("    /// `NotifyCheckCardReserved(name)` → `BP_Logic.HandleCheckCardReserved`")
    lines.append("    /// → `UtilityFunctions.isCardReserved(name)`")
    lines.append("    /// （`_deps/UtilityFunctions.g.cs:6551-6698`）。后者是：")
    lines.append("    /// <code>")
    lines.append("    /// foreach (change in DSession.cards_reserve_changes)          // 服务端下发的调档表")
    lines.append("    ///     if (change.to_be_reserved ∪ change.coming_back 含 name)")
    lines.append("    ///         if (change.activation_date &lt;= now)")
    lines.append("    ///             _isMovedToReserved = name ∈ change.to_be_reserved")
    lines.append("    ///             _isComingBack      = name ∈ change.coming_back")
    lines.append("    /// if (_isMovedToReserved || _isComingBack) return _isMovedToReserved;")
    lines.append("    /// return GetStaticCard(name).isReserved;                      // ← CDO 那个布尔字段")
    lines.append("    /// </code>")
    lines.append("    /// 也就是说：**没有被服务端调档表命中时，判据就是卡自己的 CDO `isReserved`**。")
    lines.append("    ///")
    lines.append("    /// ⚠️ 本内核没有 `DSession`，所以整表按 CDO 字段算 —— 这是**近似**，")
    lines.append("    /// 唯一会偏的地方是「调档表把某张卡 `coming_back` 回来了」的那些卡")
    lines.append("    /// （那种卡 CDO 里仍是 true、真实客户端已经算 false）。")
    lines.append("    /// 现有回放里没有能区分这两种情形的观测，所以按 CDO 走。")
    lines.append("    /// </summary>")
    lines.append("    public static readonly HashSet<string> Reserved = new(StringComparer.Ordinal)")
    lines.append("    {")
    for name in reserved:
        lines.append(f'        "{name}",')
    lines.append("    };")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// `UtilityFunctions.isCardReserved(cardName)` 的离线近似 —— 见 <see cref=\"Reserved\"/>。")
    lines.append("    ///")
    lines.append("    /// 变体名（`xxx_bal` / `xxx_vet`）先按 <see cref=\"CardDatabase.ResolveBaseName\"/>")
    lines.append("    /// 剥后缀再查，与 <see cref=\"CardInnateTable\"/> 用同一套回退规则。")
    lines.append("    /// </summary>")
    lines.append("    public static bool IsReserved(string? cardName)")
    lines.append("    {")
    lines.append("        if (string.IsNullOrEmpty(cardName))")
    lines.append("        {")
    lines.append("            return false;")
    lines.append("        }")
    lines.append("")
    lines.append("        if (Reserved.Contains(cardName))")
    lines.append("        {")
    lines.append("            return true;")
    lines.append("        }")
    lines.append("")
    lines.append("        string baseName = CardDatabase.ResolveBaseName(cardName);")
    lines.append("        return !string.Equals(baseName, cardName, StringComparison.Ordinal)")
    lines.append("               && Reserved.Contains(baseName);")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"写出 {DST.relative_to(ROOT)}：cardSet {len(CARD_SET)} 项，reserved {len(reserved)} 张")
    return 0


if __name__ == "__main__":
    sys.exit(main())
