"""从 kards-sim 的卡牌静态数据里抽出 gameplay tag，生成内核用的查表文件。

为什么需要这一步
----------------
`getHasGameplayTag` 是卡牌蓝图里判「子类型」的唯一手段 —— 例如
`card_unit_214th_amur` 的「你的 T-34 单位 +1 重甲」要判 `subtype.t34`，
`card_event_committed_crew` 的「Spitfire 费用归零」要判 `subtype.spitfire`。

这张表在**客户端 pak 里读不到**：`docs/cards.all.json` 的 CDO 里
`GameplayTags` 被序列化成了 `"UAssetAPI.PropertyTypes.Structs.StructPropertyData"`
一个类型名，值丢了；`cards.full.json`（字节码全量）里也只有 12 个 tag 字面量，
而且**只出现在调用点**，没有「哪张卡带哪个 tag」的映射。
`ref/kards-sim/cards.json` 是唯一带完整映射的现成产物（170 张卡 / 18 个 tag）。

所以这里把它的 `gameplayTags` 原样搬成一张 C# 静态表。
**不要手改生成物** —— 改这个脚本重跑。

用法（在仓库根目录）：
    python "klink bot/tools/gen-gameplay-tags.py"
输出：
    src/KLink.Bot/Effects/GameplayTagTable.cs
"""

import json
import io
import collections
import sys
from pathlib import Path

SRC = Path("ref/kards-sim/cards.json")
DST = Path("src/KLink.Bot/Effects/GameplayTagTable.cs")


def main():
    if not SRC.exists():
        print(f"找不到 {SRC}（在仓库根目录跑）")
        return 2

    cards = json.load(io.open(SRC, encoding="utf-8-sig"))

    by_card = {}
    order = []
    for c in cards:
        tags = c.get("gameplayTags") or []
        if not tags:
            continue
        name = c["id"]
        by_card[name] = sorted(tags)
        order.append(name)

    order.sort()

    tag_counts = collections.Counter()
    for tags in by_card.values():
        for t in tags:
            tag_counts[t] += 1

    lines = []
    lines.append("// <auto-generated>")
    lines.append("// 由 klink bot/tools/gen-gameplay-tags.py 从 ref/kards-sim/cards.json 生成。")
    lines.append("// 不要手改；要改就改脚本再跑（见脚本头部注释：客户端的 pak 里没有这张表）。")
    lines.append("// </auto-generated>")
    lines.append("#nullable enable")
    lines.append("")
    lines.append("namespace KLink.Bot.Effects;")
    lines.append("")
    lines.append("/// <summary>")
    lines.append(f"/// 卡名 → gameplay tag（{len(by_card)} 张卡 / {len(tag_counts)} 个 tag）。")
    lines.append("///")
    lines.append("/// 用途：实现 <c>getHasGameplayTag</c>。卡牌蓝图用它判子类型，例如")
    lines.append("/// <c>card_unit_214th_amur</c> 判 <c>subtype.t34</c>、")
    lines.append("/// <c>card_event_committed_crew</c> 判 <c>subtype.spitfire</c>。")
    lines.append("///")
    lines.append("/// ⚠️ 变体卡（<c>xxx_bal</c> / <c>xxx_vet</c>）在这里**没有条目** ——")
    lines.append("/// 查表前必须先用 <c>CardDatabase.ResolveBaseName</c> 剥后缀，")
    lines.append("/// 这和 <c>KismetLibrary</c> 找蓝图用的是同一套回退规则。")
    lines.append("/// </summary>")
    lines.append("internal static class GameplayTagTable")
    lines.append("{")
    lines.append("    private static readonly Dictionary<string, string[]> TagsByCard = new(StringComparer.Ordinal)")
    lines.append("    {")
    for name in order:
        tags = by_card[name]
        joined = ", ".join(f'"{t}"' for t in tags)
        lines.append(f'        ["{name}"] = [{joined}],')
    lines.append("    };")
    lines.append("")
    lines.append("    /// <summary>这张卡有没有这个 tag（tag 名形如 <c>subtype.t34</c>）。</summary>")
    lines.append("    public static bool Has(string cardName, string tag)")
    lines.append("    {")
    lines.append("        if (cardName.Length == 0 || tag.Length == 0)")
    lines.append("        {")
    lines.append("            return false;")
    lines.append("        }")
    lines.append("")
    lines.append("        foreach (string candidate in Candidates(cardName))")
    lines.append("        {")
    lines.append("            if (TagsByCard.TryGetValue(candidate, out string[]? tags)")
    lines.append("                && Array.IndexOf(tags, tag) >= 0)")
    lines.append("            {")
    lines.append("                return true;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        return false;")
    lines.append("    }")
    lines.append("")
    lines.append("    /// <summary>")
    lines.append("    /// 这张卡带不带**任意** tag。")
    lines.append("    ///")
    lines.append("    /// 用途：`getHasGameplayTag` 的 tag 实参在 IR 里可能被丢掉")
    lines.append("    /// （`StructConst /Script/GameplayTags.GameplayTag` 被生成器压成了 `{struct:null}`），")
    lines.append("    /// 那时只能退一步问「它是不是某种子类型」。**这不是通用正确解**，")
    lines.append("    /// 调用点同时会把 `getHasGameplayTag<ir-tag-lost>` 记进未实现统计。")
    lines.append("    /// </summary>")
    lines.append("    public static bool Any(string cardName)")
    lines.append("    {")
    lines.append("        foreach (string candidate in Candidates(cardName))")
    lines.append("        {")
    lines.append("            if (TagsByCard.ContainsKey(candidate))")
    lines.append("            {")
    lines.append("                return true;")
    lines.append("            }")
    lines.append("        }")
    lines.append("")
    lines.append("        return false;")
    lines.append("    }")
    lines.append("")
    lines.append("    private static IEnumerable<string> Candidates(string cardName)")
    lines.append("    {")
    lines.append("        yield return cardName;")
    lines.append("")
    lines.append("        string baseName = Cards.CardDatabase.ResolveBaseName(cardName);")
    lines.append("        if (!string.Equals(baseName, cardName, StringComparison.Ordinal))")
    lines.append("        {")
    lines.append("            yield return baseName;")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    DST.parent.mkdir(parents=True, exist_ok=True)
    DST.write_text("\n".join(lines), encoding="utf-8")
    print(f"写出 {len(by_card)} 张卡的 tag 映射 → {DST}")
    for t, n in sorted(tag_counts.items()):
        print(f"  {t:<26} {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
